/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/james/tas/ros/catkin/src/pendulum/srv/state.srv
 *
 */


#ifndef PENDULUM_MESSAGE_STATE_H
#define PENDULUM_MESSAGE_STATE_H

#include <ros/service_traits.h>


#include <pendulum/stateRequest.h>
#include <pendulum/stateResponse.h>


namespace pendulum
{

struct state
{

typedef stateRequest Request;
typedef stateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct state
} // namespace pendulum


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pendulum::state > {
  static const char* value()
  {
    return "5df9c4cc22276ed3d7c49b8b3485993e";
  }

  static const char* value(const ::pendulum::state&) { return value(); }
};

template<>
struct DataType< ::pendulum::state > {
  static const char* value()
  {
    return "pendulum/state";
  }

  static const char* value(const ::pendulum::state&) { return value(); }
};


// service_traits::MD5Sum< ::pendulum::stateRequest> should match 
// service_traits::MD5Sum< ::pendulum::state > 
template<>
struct MD5Sum< ::pendulum::stateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pendulum::state >::value();
  }
  static const char* value(const ::pendulum::stateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pendulum::stateRequest> should match 
// service_traits::DataType< ::pendulum::state > 
template<>
struct DataType< ::pendulum::stateRequest>
{
  static const char* value()
  {
    return DataType< ::pendulum::state >::value();
  }
  static const char* value(const ::pendulum::stateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pendulum::stateResponse> should match 
// service_traits::MD5Sum< ::pendulum::state > 
template<>
struct MD5Sum< ::pendulum::stateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pendulum::state >::value();
  }
  static const char* value(const ::pendulum::stateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pendulum::stateResponse> should match 
// service_traits::DataType< ::pendulum::state > 
template<>
struct DataType< ::pendulum::stateResponse>
{
  static const char* value()
  {
    return DataType< ::pendulum::state >::value();
  }
  static const char* value(const ::pendulum::stateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PENDULUM_MESSAGE_STATE_H
