/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/james/tas/ros/catkin/src/pendulum/msg/synch.msg
 *
 */


#ifndef PENDULUM_MESSAGE_SYNCH_H
#define PENDULUM_MESSAGE_SYNCH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pendulum
{
template <class ContainerAllocator>
struct synch_
{
  typedef synch_<ContainerAllocator> Type;

  synch_()
    : time(0.0)
    , msg(0)  {
    }
  synch_(const ContainerAllocator& _alloc)
    : time(0.0)
    , msg(0)  {
    }



   typedef double _time_type;
  _time_type time;

   typedef uint32_t _msg_type;
  _msg_type msg;




  typedef boost::shared_ptr< ::pendulum::synch_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pendulum::synch_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct synch_

typedef ::pendulum::synch_<std::allocator<void> > synch;

typedef boost::shared_ptr< ::pendulum::synch > synchPtr;
typedef boost::shared_ptr< ::pendulum::synch const> synchConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pendulum::synch_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pendulum::synch_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pendulum

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/groovy/share/std_msgs/msg'], 'pendulum': ['/home/james/tas/ros/catkin/src/pendulum/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pendulum::synch_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pendulum::synch_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pendulum::synch_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pendulum::synch_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pendulum::synch_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pendulum::synch_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pendulum::synch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "71c73720e1650008d117b8fc56ad1f04";
  }

  static const char* value(const ::pendulum::synch_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x71c73720e1650008ULL;
  static const uint64_t static_value2 = 0xd117b8fc56ad1f04ULL;
};

template<class ContainerAllocator>
struct DataType< ::pendulum::synch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pendulum/synch";
  }

  static const char* value(const ::pendulum::synch_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pendulum::synch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 time\n\
uint32 msg\n\
\n\
";
  }

  static const char* value(const ::pendulum::synch_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pendulum::synch_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time);
      stream.next(m.msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct synch_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pendulum::synch_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pendulum::synch_<ContainerAllocator>& v)
  {
    s << indent << "time: ";
    Printer<double>::stream(s, indent + "  ", v.time);
    s << indent << "msg: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PENDULUM_MESSAGE_SYNCH_H
