#ifndef _CHANNELS_H_
#define _CHANNELS_H_

//-----------------------------------------------------------------------------

#define FD_TIMER_TO_COORDINATOR_READ_CHANNEL   1001
#define FD_TIMER_TO_COORDINATOR_WRITE_CHANNEL  1002

#define FD_WAKEUP_TO_COORDINATOR_READ_CHANNEL   1003
#define FD_WAKEUP_TO_COORDINATOR_WRITE_CHANNEL  1004

#define FD_COORDINATOR_TO_PREYCONTROLLER_READ_CHANNEL   1010
#define FD_COORDINATOR_TO_PREYCONTROLLER_WRITE_CHANNEL  1011

#define FD_PREYCONTROLLER_TO_COORDINATOR_READ_CHANNEL   1012
#define FD_PREYCONTROLLER_TO_COORDINATOR_WRITE_CHANNEL  1013

#define FD_COORDINATOR_TO_PREDPLANNER_READ_CHANNEL   1014
#define FD_COORDINATOR_TO_PREDPLANNER_WRITE_CHANNEL  1015

#define FD_PREDPLANNER_TO_COORDINATOR_READ_CHANNEL   1016
#define FD_PREDPLANNER_TO_COORDINATOR_WRITE_CHANNEL  1017

#define FD_COORDINATOR_TO_PREDCONTROLLER_READ_CHANNEL   1018
#define FD_COORDINATOR_TO_PREDCONTROLLER_WRITE_CHANNEL  1019

#define FD_PREDCONTROLLER_TO_COORDINATOR_READ_CHANNEL   1020
#define FD_PREDCONTROLLER_TO_COORDINATOR_WRITE_CHANNEL  1021

//-----------------------------------------------------------------------------

#endif // _CHANNELS_H_
