% constants
%SPINDLE_LENGTH = 0.00;
BASE_LINK_LENGTH = 0.12;
MAX_STEERING_ANGLE_DEG = 30.0;
MAX_STEERING_ANGLE = MAX_STEERING_ANGLE_DEG * pi / 180.0;

STEERING_LEVER_BASE_ANGLE_DEG = 75.0;
STEERING_LEVER_BASE_ANGLE = STEERING_LEVER_BASE_ANGLE_DEG * pi / 180.0;
STEERING_LEVER_LENGTH = 0.04;
TIEROD_LENGTH = 0.1;
SPINDLE_LEVER_LENGTH = 0.055;
%SPINDLE_LEVER_BASE_ANGLE;

BASE_LINK_LENGTH_SQ = BASE_LINK_LENGTH * BASE_LINK_LENGTH;
STEERING_LEVER_LENGTH_SQ = STEERING_LEVER_LENGTH * STEERING_LEVER_LENGTH;
TIEROD_LENGTH_SQ = TIEROD_LENGTH * TIEROD_LENGTH;
SPINDLE_LEVER_LENGTH_SQ = SPINDLE_LEVER_LENGTH * SPINDLE_LEVER_LENGTH;

% compute the SPINDLE_LEVER_BASE_ANGLE
theta = STEERING_LEVER_BASE_ANGLE;
h_sq = BASE_LINK_LENGTH_SQ + STEERING_LEVER_LENGTH_SQ - 2.0 * BASE_LINK_LENGTH * STEERING_LEVER_LENGTH * cos( theta );
h = sqrt( h_sq );
rho = acos( (BASE_LINK_LENGTH_SQ + h_sq - STEERING_LEVER_LENGTH_SQ) / (2.0 * BASE_LINK_LENGTH * h) ) +...
      acos( (SPINDLE_LEVER_LENGTH_SQ + h_sq - TIEROD_LENGTH_SQ) / (2.0 * SPINDLE_LEVER_LENGTH * h) );
SPINDLE_LEVER_BASE_ANGLE = pi - rho;

steering_angle = MAX_STEERING_ANGLE;

left = -kingpin_angle( -steering_angle, STEERING_LEVER_BASE_ANGLE, BASE_LINK_LENGTH, STEERING_LEVER_LENGTH,...
                           TIEROD_LENGTH, SPINDLE_LEVER_LENGTH, SPINDLE_LEVER_BASE_ANGLE)
right = kingpin_angle( steering_angle, STEERING_LEVER_BASE_ANGLE, BASE_LINK_LENGTH, STEERING_LEVER_LENGTH,...
                           TIEROD_LENGTH, SPINDLE_LEVER_LENGTH, SPINDLE_LEVER_BASE_ANGLE)
