% constants
%SPINDLE_LENGTH = 0.00;
BASE_LINK_LENGTH = 0.12;
MAX_STEERING_ANGLE_DEG = 15.0;
MAX_STEERING_ANGLE = MAX_STEERING_ANGLE_DEG * pi / 180.0;

STEERING_LEVER_BASE_ANGLE_DEG = 75.0;
STEERING_LEVER_BASE_ANGLE = STEERING_LEVER_BASE_ANGLE_DEG * pi / 180.0;
STEERING_LEVER_LENGTH = 0.056102;
TIEROD_LENGTH = 0.1;
SPINDLE_LEVER_LENGTH = 0.055;
%SPINDLE_LEVER_BASE_ANGLE;

steering_angle = MAX_STEERING_ANGLE

[left, right] = double_four_bar( steering_angle, STEERING_LEVER_BASE_ANGLE,...
                                 BASE_LINK_LENGTH, STEERING_LEVER_LENGTH,...
                                 TIEROD_LENGTH, SPINDLE_LEVER_LENGTH)
                             
avg = (left + right) / 2.0

